### ISSUE TITLE
Building with MSVC

### ISSUE THREAD

**Issue by NicusorN5** [SydMontague/NutCracker#3]
Hi, I have found that in order to compile on Windows with VS 2022, you need 
```cmake
src/Actions.cpp
``` 
added inside the `CMakeLists.txt` file in order to compile, because there were linker errors related to the `Compare` and `Decompile` functions.

I'm not sure, I don't have a Linux machine up, but this is compiling without errors on any other systems except mine?

**Comment by SydMontague** [comment]
Thanks, this must've slipped through when the file was added.

It should be fixed now.
